# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(540, 0, 531, 131))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber.setGeometry(QtCore.QRect(70, 30, 111, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 72, 19))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.textEdit_dictout = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_dictout.setGeometry(QtCore.QRect(540, 200, 531, 361))
        self.textEdit_dictout.setObjectName("textEdit_dictout")
        self.Edit_inputword = QtWidgets.QLineEdit(self.centralwidget)
        self.Edit_inputword.setGeometry(QtCore.QRect(540, 150, 280, 40))
        self.Edit_inputword.setObjectName("Edit_inputword")
        self.Btn_dict = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_dict.setGeometry(QtCore.QRect(830, 150, 120, 40))
        self.Btn_dict.setObjectName("Btn_dict")
        self.Btn_rand5words = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_rand5words.setGeometry(QtCore.QRect(30, 10, 191, 40))
        self.Btn_rand5words.setObjectName("Btn_rand5words")
        self.Btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_add.setGeometry(QtCore.QRect(960, 150, 111, 40))
        self.Btn_add.setObjectName("Btn_add")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(540, 600, 531, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.word1_1 = QtWidgets.QLabel(self.centralwidget)
        self.word1_1.setGeometry(QtCore.QRect(30, 60, 351, 40))
        self.word1_1.setBaseSize(QtCore.QSize(4, 4))
        self.word1_1.setFrameShape(QtWidgets.QFrame.Box)
        self.word1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_1.setWordWrap(False)
        self.word1_1.setObjectName("word1_1")
        self.word1_2 = QtWidgets.QLabel(self.centralwidget)
        self.word1_2.setGeometry(QtCore.QRect(30, 200, 351, 40))
        self.word1_2.setBaseSize(QtCore.QSize(4, 4))
        self.word1_2.setFrameShape(QtWidgets.QFrame.Box)
        self.word1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_2.setWordWrap(False)
        self.word1_2.setObjectName("word1_2")
        self.word1_3 = QtWidgets.QLabel(self.centralwidget)
        self.word1_3.setGeometry(QtCore.QRect(30, 340, 351, 40))
        self.word1_3.setBaseSize(QtCore.QSize(4, 4))
        self.word1_3.setFrameShape(QtWidgets.QFrame.Box)
        self.word1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_3.setWordWrap(False)
        self.word1_3.setObjectName("word1_3")
        self.word1_4 = QtWidgets.QLabel(self.centralwidget)
        self.word1_4.setGeometry(QtCore.QRect(30, 480, 351, 40))
        self.word1_4.setBaseSize(QtCore.QSize(4, 4))
        self.word1_4.setFrameShape(QtWidgets.QFrame.Box)
        self.word1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_4.setWordWrap(False)
        self.word1_4.setObjectName("word1_4")
        self.word1_5 = QtWidgets.QLabel(self.centralwidget)
        self.word1_5.setGeometry(QtCore.QRect(30, 620, 341, 40))
        self.word1_5.setBaseSize(QtCore.QSize(4, 4))
        self.word1_5.setFrameShape(QtWidgets.QFrame.Box)
        self.word1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_5.setWordWrap(False)
        self.word1_5.setObjectName("word1_5")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_1.setGeometry(QtCore.QRect(30, 100, 441, 91))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(390, 60, 97, 40))
        self.checkBox.setObjectName("checkBox")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 240, 441, 91))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(400, 200, 97, 40))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 570, 72, 19))
        self.label.setObjectName("label")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(400, 340, 97, 40))
        self.checkBox_3.setObjectName("checkBox_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 380, 441, 91))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(400, 480, 97, 40))
        self.checkBox_4.setObjectName("checkBox_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(30, 520, 441, 91))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(400, 620, 97, 40))
        self.checkBox_5.setObjectName("checkBox_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(30, 660, 441, 91))
        self.textBrowser_5.setObjectName("textBrowser_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "万志平"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "周利华"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "万周越"))
        self.Btn_dict.setText(_translate("MainWindow", "查字典"))
        self.Btn_rand5words.setText(_translate("MainWindow", "随机生成五个英语单词"))
        self.Btn_add.setText(_translate("MainWindow", "加入词库"))
        self.word1_1.setText(_translate("MainWindow", "1"))
        self.word1_2.setText(_translate("MainWindow", "1"))
        self.word1_3.setText(_translate("MainWindow", "1"))
        self.word1_4.setText(_translate("MainWindow", "1"))
        self.word1_5.setText(_translate("MainWindow", "1"))
        self.checkBox.setText(_translate("MainWindow", "加入学习"))
        self.checkBox_2.setText(_translate("MainWindow", "加入学习"))
        self.label.setText(_translate("MainWindow", "学习曲线"))
        self.checkBox_3.setText(_translate("MainWindow", "加入学习"))
        self.checkBox_4.setText(_translate("MainWindow", "加入学习"))
        self.checkBox_5.setText(_translate("MainWindow", "加入学习"))

